### ISSUE TITLE
Profile-page stats doesn't navigate anywhere

### ISSUE THREAD

**Issue by SwapplerDEV** [SwapplerDEV/SwapplerApp#21]
On the profilepage there are stats
- followers
- following
- items on sale

They should all be links. Followers should link to
![followers_tabs](https://cloud.githubusercontent.com/assets/13752872/10412143/1150424e-6f85-11e5-8bd8-6719acf5814f.png)

Following should link to
![following_tabs](https://cloud.githubusercontent.com/assets/13752872/10412144/1e956dd0-6f85-11e5-906c-98dbf08fc686.png)

Items on sale should link to
![onsale](https://cloud.githubusercontent.com/assets/13752872/10412147/299dda64-6f85-11e5-9c26-9a163bfd4833.png)

**Comment by andeluvian** [comment]
This is a new feature that was missing from Swappler App alpha version, this app is based on the alpha because there was no original documentation for this application, documentation was created at the same time the application was being developed, thus this is a new feature new task. I will reassign this from bugs to new feature new task

**Comment by andeluvian** [comment]
Features is enabled in previous release
